import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Copyright from "./components/Copyright";
import ProductsContextProvider from "./context/ProductsContextProvider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Cafe de altura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ProductsContextProvider>
          <Navbar />
          {children}

          <Copyright />
        </ProductsContextProvider>
      </body>
    </html>
  );
}
